spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db_2005?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.qf.student_208_308.web_demo.pojo